name-template: "Example title - v2025.12.0b1"
tag-template: "v2025.12.0b1"

exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Breaking changes"
    labels:
      - "breaking"
  - title: "Bug fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Translation"
    collapse-after: 2
    labels:
      - "translation"
  - title: "Dependencies"
    collapse-after: 2
    labels:
      - "dependencies"
      - "dependency"
  - title: "Maintenance"
    label: "maintenance"
  - title: "Code quality and optimizations"
    label: "code quality"
  - title: "Development tools"
    labels:
      - "development tools"
      - "dev-tools"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads-pre/$OWNER/$REPOSITORY/v2025.12.0b1/total.svg)]
  (https://github.com/$OWNER/$REPOSITORY/releases/v2025.12.0b1)

  <!--
  ### Checklist for release
  - Download translations PR from Lokalise
  - Run ruff linter
  - Run make bump - select proper variant in Makefile
  - Review the draft below and update if needed
  -->

  ## Notable Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"
      - ".github/*"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "code quality"
    title:
      - "lint"
  - label: "translation"
    title:
      - "Lokalise:"
    files:
      - "**/translations/*.json"
  - label: "development tools"
    files:
      - ".devcontainer/*"
      - ".devcontainer.json"
      - "Makefile"
      - "setup.cfg"
